<a href="https://colab.research.google.com/github/CE334/CE334_230333_Chinthala_Manasa/blob/main/Chinthala_Manasa_230333_Lab_0_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

# CE334: Modern Methods in Geoinformatics
# Lab Assignment 0
# Introduction to Python and Scientific Computing


import numpy as np
import pandas as pd


In [3]:
#1st question
# Manual Method
# A row vector is just a simple list of numbers
row_vec_manual = np.array([1, 2, 3, 4])
# A column vector needs to be written as a list of lists
col_vec_manual = np.array([[1], [2], [3], [4]])

print("Manual Row Vector:", row_vec_manual)
print("Manual Column Vector:\n", col_vec_manual)

# Input Method
row_input = list(map(float, input("Enter row vector elements: ").split()))
row_vec_input = np.array(row_input)

col_input = list(map(float, input("Enter column vector elements: ").split()))
col_vec_input = np.array(col_input).reshape(-1, 1)

print("Input Row Vector:", row_vec_input)
print("Input Column Vector:\n", col_vec_input)


Manual Row Vector: [1 2 3 4]
Manual Column Vector:
 [[1]
 [2]
 [3]
 [4]]
Enter row vector elements: 1 2 3 4
Enter column vector elements: 5 6 7 8
Input Row Vector: [1. 2. 3. 4.]
Input Column Vector:
 [[5.]
 [6.]
 [7.]
 [8.]]


In [5]:
# 2nd question
# Manual matrix
# This is our main matrix and we name it 'a'
a_manual = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

# Input method
print("Enter 25 elements for 5x5 matrix:")
a_input = np.array(list(map(float, input().split()))).reshape(5, 5)

# Choose one as matrix a
a = a_manual

print("Matrix a:\n", a)

Enter 25 elements for 5x5 matrix:
1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5
Matrix a:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [7]:
# 3rd question
# Python indexing starts from 0
# So 3rd row means index 2
third_row = a[2]
print("3rd Row of matrix a:", third_row)


3rd Row of matrix a: [11 12 13 14 15]


In [8]:
# 4th question
# ':' means all rows
# Column index 3 gives the 4th column
fourth_col = a[:, 3]
print("4th Column of matrix a:", fourth_col)


4th Column of matrix a: [ 4  9 14 19 24]


In [9]:
# 5th question
# Sorting each row separately
row_sorted = np.sort(a, axis=1)
# Sorting each column separately
col_sorted = np.sort(a, axis=0)

print("Row-wise Sorted Matrix:\n", row_sorted)
print("Column-wise Sorted Matrix:\n", col_sorted)


Row-wise Sorted Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Column-wise Sorted Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [11]:
# 6th quesion
# Creating a new matrix 'b' so original matrix 'a' is not changed
b = a.copy()
# Checking each element one by one
# If value is greater than 2, multiply it by 10
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        if a[i, j] > 2:
            b[i, j] = a[i, j] * 10

print("Matrix b after condition:\n", b)


Matrix b after condition:
 [[  1   2  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]
 [210 220 230 240 250]]


In [12]:
# 7th question
# Simple element-wise addition
addition = a + b
print("a + b:\n", addition)


a + b:
 [[  2   4  33  44  55]
 [ 66  77  88  99 110]
 [121 132 143 154 165]
 [176 187 198 209 220]
 [231 242 253 264 275]]


In [13]:
# 8th question
# Subtracting b from a element by element
subtraction = a - b
print("a - b:\n", subtraction)


a - b:
 [[   0    0  -27  -36  -45]
 [ -54  -63  -72  -81  -90]
 [ -99 -108 -117 -126 -135]
 [-144 -153 -162 -171 -180]
 [-189 -198 -207 -216 -225]]


In [14]:
# 9th question
# Element-wise multiplication
elementwise_mul = a * b

# Matrix multiplication
matrix_mul = np.dot(a, b)

print("Element-wise Multiplication:\n", elementwise_mul)
print("Matrix Multiplication:\n", matrix_mul)


Element-wise Multiplication:
 [[   1    4   90  160  250]
 [ 360  490  640  810 1000]
 [1210 1440 1690 1960 2250]
 [2560 2890 3240 3610 4000]
 [4410 4840 5290 5760 6250]]
Matrix Multiplication:
 [[ 2141  2282  2450  2600  2750]
 [ 4846  5192  5700  6100  6500]
 [ 7551  8102  8950  9600 10250]
 [10256 11012 12200 13100 14000]
 [12961 13922 15450 16600 17750]]


In [15]:
# 10 th question
# Dividing every element by 18
a_div = a / 18
b_div = b / 18

print("Matrix a / 18:\n", a_div)
print("Matrix b / 18:\n", b_div)


Matrix a / 18:
 [[0.05555556 0.11111111 0.16666667 0.22222222 0.27777778]
 [0.33333333 0.38888889 0.44444444 0.5        0.55555556]
 [0.61111111 0.66666667 0.72222222 0.77777778 0.83333333]
 [0.88888889 0.94444444 1.         1.05555556 1.11111111]
 [1.16666667 1.22222222 1.27777778 1.33333333 1.38888889]]
Matrix b / 18:
 [[ 0.05555556  0.11111111  1.66666667  2.22222222  2.77777778]
 [ 3.33333333  3.88888889  4.44444444  5.          5.55555556]
 [ 6.11111111  6.66666667  7.22222222  7.77777778  8.33333333]
 [ 8.88888889  9.44444444 10.         10.55555556 11.11111111]
 [11.66666667 12.22222222 12.77777778 13.33333333 13.88888889]]


In [17]:
# 11 question
# Inverse
# a_inv = np.linalg.inv(a)
# b_inv = np.linalg.inv(b)

# Rank
a_rank = np.linalg.matrix_rank(a)
b_rank = np.linalg.matrix_rank(b)

# Condition number
a_cond = np.linalg.cond(a)
b_cond = np.linalg.cond(b)

# Singular Value Decomposition
a_svd = np.linalg.svd(a)
b_svd = np.linalg.svd(b)

# Norm
a_norm = np.linalg.norm(a)
b_norm = np.linalg.norm(b)

print("Rank of a:", a_rank)
print("Condition number of a:", a_cond)
print("Norm of a:", a_norm)

# Calculate and print the determinant of 'a' to confirm singularity
a_det = np.linalg.det(a)
print("Determinant of a:", a_det)

# Since 'b' might also be singular due to its construction from 'a', let's check its determinant as well.
b_det = np.linalg.det(b)
print("Determinant of b:", b_det)


Rank of a: 2
Condition number of a: 3.5675570478720614e+17
Norm of a: 74.33034373659252
Determinant of a: 0.0
Determinant of b: 0.0


In [19]:
# 12th question
# Norm
# Length (magnitude) of the column vector
col_norm = np.linalg.norm(col_vec_manual)

# Inner Product
inner_product = np.dot(col_vec_manual.flatten(), col_vec_manual.flatten())

# Outer Product
outer_product = np.outer(col_vec_manual, col_vec_manual)

print("Norm of Column Vector:", col_norm)
print("Inner Product:", inner_product)
print("Outer Product:\n", outer_product)


Norm of Column Vector: 5.477225575051661
Inner Product: 30
Outer Product:
 [[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [24]:
# 13th question
# This function calculates derivative using numerical methods
# By default, central difference method is used
def derivative(f, a, method='central', h=0.01):
    if method == 'forward':
        return (f(a + h) - f(a)) / h
    elif method == 'backward':
        return (f(a) - f(a - h)) / h
    else:
        return (f(a + h) - f(a - h)) / (2 * h)
# Define functions
f1 = lambda x: np.exp(x)
f2 = lambda x: np.cos(x)

x_val = 0.5

print("Derivative of e^x at x=0.5:", derivative(f1, x_val))
print("Derivative of cos(x) at x=0.5:", derivative(f2, x_val))




Derivative of e^x at x=0.5: 1.648748749525375
Derivative of cos(x) at x=0.5: -0.4794175482185081


In [26]:
# 14th question
aws_data = pd.read_csv("AWS_Data.csv")
print(aws_data.head())


                  created_at  entry_id  Soil Temperature  Soil Moisture  \
0  2022-12-14T14:19:11+05:30     10830             21.06            817   
1  2022-12-14T14:20:13+05:30     10831             21.06            817   
2  2022-12-14T14:21:15+05:30     10832             21.06            817   
3  2022-12-14T14:22:18+05:30     10833             21.06            817   
4  2022-12-14T14:23:20+05:30     10834             21.06            817   

   Wind Speed  Rainfall  Temperature  Humidity  Pressure  Battery Voltage  
0         0.0      0.25        25.38     45.09      1.94             4.14  
1         0.0      0.25        25.27     46.52      1.94             4.14  
2         0.0      0.25        25.34     45.79      1.94             4.14  
3         0.0      0.25        25.13     44.91      1.94             4.15  
4         0.0      0.25        24.95     45.12      1.94             4.15  
